unbind r
unbind C-b
bind r source-file ~/.tmux.conf

set -g prefix C-Space
set-option -g status-position top

# Turn on the mouse support
set -g mouse on 

# Vim motion
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'catpuccin/tmux'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux)
run '~/.tmux/plugins/tpm/tpm'
